vpc_cidr           = "10.3.0.0/16"
public_subnet_cidr = "10.3.1.0/24"
instance_type      = "t3.micro"
Operation_System   = "redhat"
public_key_name    = "prod-key"
private_key        = "prod.pem"
