vpc_cidr           = "10.1.0.0/16"
public_subnet_cidr = "10.1.1.0/24"
instance_type      = "t3.micro"
Operation_System   = "ubuntu"
public_key_name    = "uat-key"
private_key        = "uat.pem"
